/* See LICENSE in the root of this project for change info */

#include "hack.h"
#include "display.h"

#include <stdio.h>
#include <string.h>

static void var_number(FILE *f, const char *name, int value) {
    fprintf(f, "exports.%s = %d;\n", name, value);
}

int main(int argc, char *argv[]) {
    char *dest = argv[1];

    FILE *f = fopen(dest, "w");
    if (!f) {
        fprintf(stderr, "Unable to open %s\n", dest);
        return -1;
    }

    fprintf(f, "%s\n",  "// This source file is auto-generated by 'js_constants'\n");
    var_number(f, "COLNO", COLNO);
    var_number(f, "ROWNO", ROWNO);
    var_number(f, "GLYPH_MON_OFF", GLYPH_MON_OFF);
    var_number(f, "GLYPH_PET_OFF", GLYPH_PET_OFF);
    var_number(f, "GLYPH_INVIS_OFF", GLYPH_INVIS_OFF);
    var_number(f, "GLYPH_DETECT_OFF", GLYPH_DETECT_OFF);
    var_number(f, "GLYPH_BODY_OFF", GLYPH_BODY_OFF);
    var_number(f, "GLYPH_RIDDEN_OFF", GLYPH_RIDDEN_OFF);
    var_number(f, "GLYPH_OBJ_OFF", GLYPH_OBJ_OFF);
    var_number(f, "GLYPH_CMAP_OFF", GLYPH_CMAP_OFF);
    var_number(f, "GLYPH_EXPLODE_OFF", GLYPH_EXPLODE_OFF);
    var_number(f, "GLYPH_ZAP_OFF", GLYPH_ZAP_OFF);
    var_number(f, "GLYPH_SWALLOW_OFF", GLYPH_SWALLOW_OFF);
    var_number(f, "GLYPH_WARNING_OFF", GLYPH_WARNING_OFF);
    var_number(f, "MAX_GLYPH", MAX_GLYPH);

    fclose(f);
    return 0;
}
