/* See LICENSE in the root of this project for change info */

#include "objclass.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#define OUTPUT_FILE_PATH_TEMPLATE "../build/%s"

static char filename[60];
static char temp[32];
static FILE *ofp;
static const char *Dont_Edit_Code = "// This source file is auto-generated by 'make_onames'\n";

static char * eos (char *s) {
    while (*s) s++;
    return s;
}

static char * tmpdup (const char *str) {
    static char buf[128];

    if (!str)
        return NULL;

    strncpy(buf, str, 127);
    return buf;
}

// limit a name to 30 characters length
static char * limit (char *name, int pref) {
    strncpy(temp, name, pref ? 26 : 30);
    temp[pref ? 26 : 30] = 0;
    return temp;
}

static void do_objs (void) {
    int i, sum = 0;
    char *c, *objnam;
    int nspell = 0;
    int prefix = 0;
    char class = '\0';
    bool sumerr = false;

    filename[0]='\0';
    sprintf(eos(filename), OUTPUT_FILE_PATH_TEMPLATE, "onames.h");
    if (!(ofp = fopen(filename, "w+"))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    fprintf(ofp,"%s\n", Dont_Edit_Code);
    fprintf(ofp,"#ifndef ONAMES_H\n#define ONAMES_H\n\n");

    for(i = 0; !i || objects[i].oc_class != ILLOBJ_CLASS; i++) {
        objects[i].oc_name_idx = objects[i].oc_descr_idx = i;   /* init */
        if (!(objnam = tmpdup(OBJ_NAME(objects[i])))) continue;

        /* make sure probabilities add up to 1000 */
        if(objects[i].oc_class != class) {
            if (sum && sum != 1000) {
                fprintf(stderr, "prob error for class %d (%d%%)",
                        class, sum);
                (void) fflush(stderr);
                sumerr = true;
            }
            class = objects[i].oc_class;
            sum = 0;
        }

        for (c = objnam; *c; c++)
            if (*c >= 'a' && *c <= 'z') *c -= (char)('a' - 'A');
            else if (*c < 'A' || *c > 'Z') *c = '_';

        switch (class) {
            case WAND_CLASS:
                fprintf(ofp,"#define\tWAN_"); prefix = 1; break;
            case RING_CLASS:
                fprintf(ofp,"#define\tRIN_"); prefix = 1; break;
            case POTION_CLASS:
                fprintf(ofp,"#define\tPOT_"); prefix = 1; break;
            case SPBOOK_CLASS:
                fprintf(ofp,"#define\tSPE_"); prefix = 1; nspell++; break;
            case SCROLL_CLASS:
                fprintf(ofp,"#define\tSCR_"); prefix = 1; break;
            case AMULET_CLASS:
                /* avoid trouble with stupid C preprocessors */
                fprintf(ofp,"#define\t");
                if(objects[i].oc_material == PLASTIC) {
                    fprintf(ofp,"FAKE_AMULET_OF_YENDOR\t%d\n", i);
                    prefix = -1;
                    break;
                }
                break;
            default:
                fprintf(ofp,"#define\t");
        }
        if (prefix >= 0)
            fprintf(ofp,"%s\t%d\n", limit(objnam, prefix), i);
        prefix = 0;

        sum += objects[i].oc_prob;
    }

    /* check last set of probabilities */
    if (sum && sum != 1000) {
        fprintf(stderr, "prob error for class %d (%d%%)", class, sum);
        (void) fflush(stderr);
        sumerr = true;
    }

    fprintf(ofp,"#define\tLAST_GEM\t(JADE)\n");
    fprintf(ofp,"#define\tMAXSPELL\t%d\n", nspell+1);
    fprintf(ofp,"#define\tNUM_OBJECTS\t%d\n", i);
    fprintf(ofp,"\n#endif /* ONAMES_H */\n");
    fclose(ofp);
    if (sumerr) exit(EXIT_FAILURE);
    return;
}

int main(int argc, char *argv[]) {
    do_objs();
}
