/* See LICENSE in the root of this project for change info */

#include "permonst.h"
#include "monsym.h"

#include <stdio.h>
#include <string.h>

static char * tmpdup (const char *str) {
    static char buf[128];

    if (!str)
        return NULL;

    strncpy(buf, str, 127);
    return buf;
}

int main(int argc, char *argv[]) {
    char *dest = argv[1];

    FILE *f = fopen(dest, "w");
    if (!f) {
        fprintf(stderr, "Unable to open %s\n", dest);
        return -1;
    }

    fprintf(f, "// This source file is auto-generated by 'make_pm'\n");
    fprintf(f, "\n");
    fprintf(f, "#ifndef PM_H\n");
    fprintf(f, "#define PM_H\n");
    fprintf(f, "\n");
    fprintf(f, "enum {\n");
    fprintf(f, "    PM_PLAYERMON = -1,\n");
    int i;
    for (i = 0; mons[i].mlet; i++) {
        fprintf(f, "    PM_");
        if (mons[i].mlet == S_HUMAN && !strncmp(mons[i].mname, "were", 4))
            fprintf(f, "HUMAN_");
        char *c, *nam;
        for (nam = c = tmpdup(mons[i].mname); *c; c++)
            if (*c >= 'a' && *c <= 'z')
                *c -= (char)('a' - 'A');
            else if (*c < 'A' || *c > 'Z')
                *c = '_';
        fprintf(f, "%s = %d,\n", nam, i);
    }
    fprintf(f, "};\n");
    fprintf(f, "\n");
    fprintf(f, "enum { NUMMONS = %d };\n", i);

    fprintf(f, "\n#endif /* PM_H */\n");
    fclose(f);
    return 0;
}
